// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoogyifcgcajzigjcssm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpvb2d5aWZjZ2NhanppZ2pjc3NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODk0OTEsImV4cCI6MjA2MDk2NTQ5MX0.2Kb0DUHqlpzdKnTazjgQy30g-y9cJR0Rhde8kJIk1QM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);